version: '3'

services:
  app:
    build: .
    container_name: get-streamclassic-data
    tty: true
    volumes:
      - ./sample:/usr/src/sample
    working_dir: "/usr/src/sample"
    env_file:
      - web-variables.env
